create table revinfo (rev integer generated by default as identity, revtstmp bigint, primary key (rev));
create table vehicle_group_aud (id binary not null, rev integer not null, revtype tinyint, created_at bigint, creator_id binary, fleet_id binary, name varchar(255), updated_at bigint, primary key (id, rev));
create table vehicle_group_vehicles_aud (rev integer not null, vehicle_group_id binary not null, vehicles_id binary not null, revtype tinyint, primary key (rev, vehicle_group_id, vehicles_id));
alter table vehicle_group_aud add constraint FKt9vu7b5iyo769i2f8i9ivtndj foreign key (rev) references revinfo;
alter table vehicle_group_vehicles_aud add constraint FKiohwwg4il5lp4gms56aafoof2 foreign key (rev) references revinfo;
